app:
  mock: false


video:
  source: "https://www.bilibili.com/video/BV1NCgVzoEG9/?vd_source=1ce32605a59581a6ec6d48f9eaa72d66"
  download_path: "./downloads"
  language: "zh"
  quality: "best"
  login:
    method: "qrcode"  # qrcode / account
    username: ""
    password: ""

ai:
  provider: "openai"
  model: "gpt-4o-mini"
  temperature: 0.7

providers:
  openai:
    api_key: "sk-xxxx"
    endpoint: "https://api.openai.com/v1/chat/completions"
    prompt_template: "..."

notion:
  enable: true
  token: "notion-secret-xxx"
  database_id: "xxxx"
  tags: ["AI 学习", "视频总结"]
  publish_status: "Published"
