# =============================
# 全局应用配置
# =============================
app:
  mock: false           # 是否启用 mock 模式（测试时可用）
  log_level: "INFO"     # 日志等级：DEBUG / INFO / WARNING / ERROR

# =============================
# 视频下载配置
# =============================
video:
  # 视频源 URL（单 P 或合集）
  url: "https://www.bilibili.com/video/BV1NCgVzoEG9/"  # 视频链接
  # 输出目录（视频 /音频 /帧等保存根目录）
  download_path: "./downloads"
  language: "zh"
  frame_interval: 10     # 关键帧提取间隔（秒）
  quality: "best"        # 支持 best, 1080, 720 等
  login:
    method: "cookies"    # 登录方式：cookies / qrcode / account
    cookies_path: "./config/bilibili_cookies.txt"
    username: ""         # account 登录模式需要
    password: ""         # account 登录模式需要


# =============================
# Notion 同步配置（可选）
# =============================
notion:
  enable: true
  token: "notion-secret-xxx"
  database_id: "xxxx-xxxx-xxxx"
  tags: [ "AI 学习", "视频总结" ]
  publish_status: "Published"

# =============================
# 输出配置
# =============================
output:
  markdown_path: "./notes"
  include_images: true
  mermaid_diagrams: true
  auto_summary_sections: [ "概述", "原理图", "代码讲解", "应用场景" ]


# =============================
# AI 配置
# =============================
ai:
  provider: "qwen"       # 可选：openai / anthropic / gemini / qwen / ernie / vllm / local
  model: "qwen-turbo"
  temperature: 0.7

# =============================
# AI 供应商统一配置
# =============================
providers:
  openai:
    api_key: ${OPENAI_API_KEY}
    endpoint: "https://api.openai.com/v1/chat/completions"
    prompt_template: |
      你是专业技术文档撰写者，请基于以下视频内容（转写+字幕）生成结构严谨的Markdown笔记：
      
      【核心要求】
      1. 结构：包含「概述」「核心原理」「关键步骤」「代码/案例」「总结」5个一级章节
      2. 图文：在相关章节插入图片引用（图片路径：{{frames}}），描述画面核心信息
      3. 细节：保留技术术语、数据、代码片段，补充逻辑衔接语句
      4. 格式：代码用```包裹，列表用-或1.，重要内容加粗
      
      【视频内容】
      {{transcript}}
      
      【可用图片】
      {{frames}}

  # 豆包配置
  doubao:
    api_key: ${DOUBAO_API_KEY}
    endpoint: "https://api.doubao.com/v1/chat/completions"  # 摘要接口
    audio_endpoint: "https://api.doubao.com/v1/audio/transcriptions"  # 转写接口
    prompt_template: |
      基于以下视频内容生成技术笔记，包含「概述」「核心原理」「代码案例」「总结」：
      {{transcript}}
      可用图片：{{frames}}

  # DeepSeek配置
  deepseek:
    api_key: ${DEEPSEEK_API_KEY}
    endpoint: "https://api.deepseek.com/v1/chat/completions"  # 摘要接口
    audio_endpoint: "https://api.deepseek.com/v1/audio/transcribe"  # 转写接口
    prompt_template: |
      基于以下视频内容生成技术笔记，包含「概述」「核心原理」「代码案例」「总结」：
      {{transcript}}
      可用图片：{{frames}}

  # 通义千问完整配置
  qwen:
    api_key: ${QWEN_API_KEY}
    endpoint: "https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation"
    prompt_template: |
      基于以下视频内容生成技术笔记，包含「概述」「核心原理」「代码案例」「总结」：
      {{transcript}}
      可用图片：{{frames}}

  local:
    summarizer: "rules" # 可选：rules / light-nlp
    transcriber: "whisper" # 可选：whisper / local
