# =============================
# 全局应用配置
# =============================
app:
  mock: false           # 是否启用 mock 模式（测试时可用）
  log_level: "INFO"     # 日志等级：DEBUG / INFO / WARNING / ERROR

# =============================
# 视频下载配置
# =============================
video:
  url: "https://www.bilibili.com/video/BV1NCgVzoEG9/"  # 视频链接
  download_path: "./downloads"
  language: "zh"
  quality: "best"        # 支持 best, 1080, 720 等
  login:
    method: "cookies"    # 登录方式：cookies / qrcode / account
    cookies_path: "./config/bilibili_cookies.txt"
    username: ""         # account 登录模式需要
    password: ""         # account 登录模式需要
  frame_interval: 10     # 关键帧提取间隔（秒）

# =============================
# AI 配置
# =============================
ai:
  provider: "local"       # 可选：openai / anthropic / gemini / qwen / ernie / vllm / local
  model: "gpt-4o-mini"
  temperature: 0.7

# =============================
# AI 供应商统一配置
# =============================
providers:
  openai:
    api_key: "sk--xxx"
    endpoint: "https://api.openai.com/v1/chat/completions"
    prompt_template: |
      你是专业技术文档撰写者，请基于以下视频内容（转写+字幕）生成结构严谨的Markdown笔记：
      
      【核心要求】
      1. 结构：包含「概述」「核心原理」「关键步骤」「代码/案例」「总结」5个一级章节
      2. 图文：在相关章节插入图片引用（图片路径：{{frames}}），描述画面核心信息
      3. 细节：保留技术术语、数据、代码片段，补充逻辑衔接语句
      4. 格式：代码用```包裹，列表用-或1.，重要内容加粗
      
      【视频内容】
      {{transcript}}
      
      【可用图片】
      {{frames}}

  anthropic:
    api_key: "claude-xxx"
    endpoint: "https://api.anthropic.com/v1/messages"

  ernie:
    api_key: "xxxx"
    endpoint: "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/{{model}}"

  gemini:
    api_key: "AIza-xxxx"
    endpoint: "https://generativelanguage.googleapis.com/v1beta/models/{{model}}:generateContent"

  qwen:
    api_key: "ak-xxxx"
    endpoint: "https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation"

  local:
    summarizer: "rules" # 可选：rules / light-nlp
    transcriber: "whisper" # 可选：whisper / local


# =============================
# 输出配置
# =============================
output:
  markdown_path: "./notes"
  include_images: true
  mermaid_diagrams: true
  auto_summary_sections: ["概述", "原理图", "代码讲解", "应用场景"]

# =============================
# Notion 同步配置（可选）
# =============================
notion:
  enable: true
  token: "notion-secret-xxx"
  database_id: "xxxx-xxxx-xxxx"
  tags: ["AI 学习", "视频总结"]
  publish_status: "Published"